BaseURL: "http://new.imint.se"
languageCode: "sv-se"
title: "Imint"
MetaDataFormat: "toml"
blackfriday:
  extensions:
    - hardLineBreak
theme: hugo-vidhance-theme
menu:
  main:
    - name: "Lösningar"
      weight: 15
      URL: "/losningar/"
    - name: "Nyheter"
      weight: 15
      URL: "/nyheter/"
